create_appointment:
  synonyms:
    - "create appointment"
    - "schedule"
    - "add appointment"
    - "make appointment"
    - "termin erstellen"
    - "termin anlegen"
    - "termin eintragen"
    - "termin buchen"
    - "neuen termin"
    - "booking appointment"
    - "book appointment"
  fallback_title: "Ohne Titel"

list_appointments:
  synonyms:
    - "list appointments"
    - "show appointments"
    - "upcoming"
    - "zeige termine"
    - "liste termine"
    - "alle termine"
    - "terminübersicht"
    - "was steht an"

update_appointment:
  synonyms:
    - "update appointment"
    - "reschedule"
    - "change appointment"
    - "termin ändern"
    - "termin verschieben"
    - "termin neu planen"
    - "zeit ändern"

delete_appointment:
  synonyms:
    - "delete appointment"
    - "remove appointment"
    - "cancel appointment"
    - "termin löschen"
    - "termin entfernen"
    - "termin absagen"
